name: Release

on:
  push:
    tags:
    - '*.*.*'

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Build and Test
      env:
        PACKAGE_VERSION: ${{ github.ref_name }}
      run: ./Build.ps1

    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./Push.ps1

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        if-no-files-found: error
        retention-days: 7
        path: artifacts/**/*