name: Release

on:
  push:
    tags:
    - '*.*.*'

# on:
#   workflow_dispatch: # Allow running the workflow manually from the GitHub UI
#   push:
#     branches:
#       - 'main'       # Run the workflow when pushing to the main branch
#   pull_request:
#     branches:
#       - '*'          # Run the workflow for all pull requests
#   release:
#     types:
#       - published    # Run the workflow when a new GitHub release is published


permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - name: Install SQL Local DB
    #   run: ./Setup.ps1
    #   shell: pwsh
    # - name: Build and Test
    #   run: ./Build.ps1
    #   shell: pwsh
    # - name: Push to MyGet
    #   env:
    #     NUGET_URL: https://www.myget.org/F/automapperdev/api/v3/index.json
    #     NUGET_API_KEY: ${{ secrets.MYGET_CI_API_KEY }}
    #   run: ./Push.ps1
    #   shell: pwsh
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./Push.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*